import type { Metadata } from "next";
import { Inter, Archivo } from 'next/font/google';
import "./globals.css";
import Navbar from "@/src/components/Navbar";
import { AuthProvider } from "@/src/context/AuthContext";

// Fonte para leitura e textos corridos
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter'
});

// Fonte para títulos e botões (estilo Smart)
const archivo = Archivo({
  subsets: ['latin'],
  weight: ['400', '700', '900'],
  style: ['normal', 'italic'],
  variable: '--font-archivo',
});

export const metadata: Metadata = {
  title: "BXVS Connect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${archivo.variable}`}
      >
        <AuthProvider>
          {children}
          <Navbar />
        </AuthProvider>
      </body>
    </html>
  );
}
